# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seed_train_extractor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(908, 834)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vtk_widget = QVTKRenderWindowInteractor(self.centralwidget)
        self.vtk_widget.setGeometry(QtCore.QRect(10, 50, 871, 701))
        self.vtk_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.vtk_widget.setObjectName("vtk_widget")
        self.btn_train = QtWidgets.QPushButton(self.centralwidget)
        self.btn_train.setEnabled(True)
        self.btn_train.setGeometry(QtCore.QRect(780, 770, 101, 21))
        self.btn_train.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.btn_train.setObjectName("btn_train")
        self.lbl_recording = QtWidgets.QLabel(self.centralwidget)
        self.lbl_recording.setGeometry(QtCore.QRect(640, 50, 240, 135))
        self.lbl_recording.setToolTipDuration(14)
        self.lbl_recording.setAutoFillBackground(False)
        self.lbl_recording.setStyleSheet("")
        self.lbl_recording.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_recording.setText("")
        self.lbl_recording.setIndent(-1)
        self.lbl_recording.setObjectName("lbl_recording")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setEnabled(False)
        self.btn_next.setGeometry(QtCore.QRect(850, 20, 31, 23))
        self.btn_next.setObjectName("btn_next")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 20, 781, 21))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.btn_previous = QtWidgets.QPushButton(self.centralwidget)
        self.btn_previous.setEnabled(False)
        self.btn_previous.setGeometry(QtCore.QRect(810, 20, 31, 23))
        self.btn_previous.setObjectName("btn_previous")
        self.chk_view_rgb = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_view_rgb.setGeometry(QtCore.QRect(10, 770, 131, 23))
        self.chk_view_rgb.setObjectName("chk_view_rgb")
        self.vtk_widget.raise_()
        self.btn_train.raise_()
        self.btn_next.raise_()
        self.lbl_recording.raise_()
        self.horizontalSlider.raise_()
        self.btn_previous.raise_()
        self.chk_view_rgb.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vizualizing propagation"))
        self.btn_train.setText(_translate("MainWindow", "TRAIN"))
        self.btn_next.setText(_translate("MainWindow", ">"))
        self.btn_previous.setText(_translate("MainWindow", "<"))
        self.chk_view_rgb.setText(_translate("MainWindow", "View RGB image"))
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
